#!/usr/bin/env bash

# Function to display usage information
display_usage() {
  echo "Usage: $0 <domain> [subdomain]"
}

# Function to get DNS information for a subdomain
get_dns_info() {
  local domain="$1"
  local subdomain="$2"
  dig_output=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
  record_type=$(echo "$dig_output" | awk '/A/ {print "A"} /CNAME/ {print "CNAME"}')
  destination=$(echo "$dig_output" | awk '/IN/ {print $NF}')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check the number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  display_usage
  exit 1
fi

domain="$1"
subdomain="$2"

# If subdomain is not provided, display information for default subdomains
if [ -z "$subdomain" ]; then
  get_dns_info "$domain" "www"
  get_dns_info "$domain" "lb-01"
  get_dns_info "$domain" "web-01"
  get_dns_info "$domain" "web-02"
else
  # Display information for the specified subdomain
  get_dns_info "$domain" "$subdomain"
fi
