#!/usr/bin/env bash
# Script Description: Install and configure HAproxy on a new Ubuntu machine.
# Install HAproxy
# Configure HAproxy
# Enable HAproxy init script
# Restart HAproxy to apply changes

sudo apt-get -y update
sudo apt-get install -y haproxy

server_config=\
"
frontend  saleh
        bind *:80
        mode http
        default_backend medchakir
backend saleh
        balance roundrobin
        server 448547-web-01 100.26.252.120:80 check
        server 448547-web-02 52.91.101.188:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
