#!/usr/bin/env bash
# Script Description: Install and configure HAproxy on a new Ubuntu machine.
# Install HAproxy
# Configure HAproxy
# Enable HAproxy init script
# Restart HAproxy to apply changes

# Update package lists and install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 448547-web-01:80 check
    server web-02 448547-web-02:80 check
EOT

# Enable HAProxy as a service
sudo systemctl enable haproxy

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy
